const path = require('path');
class CategoryCtl {
    categoryList(ctx) {
        // 返回结果
     let categoryList = {"msg":"success","errorCode":0,"data":{"data":[{"created_at":"2019-08-20","id":12,"title":"DNS预解析","author":"梁凤波","cover":"http://cdn.boblog.com/FvXZiyYKefJ9_HrxbeRiU2jNVJC2","category_id":"5","browse":1237,"comments_nums":35,"category_detail":{"id":5,"name":"Node.js","key":"nodejs","parent_id":0}},{"created_at":"2019-07-09","id":11,"title":"理解JavaScript执行上下文","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":1372,"comments_nums":53,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-27","id":9,"title":"ES6解构-对象解构","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":787,"comments_nums":26,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-26","id":8,"title":"ES6块级作用域-let-const","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":333,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-25","id":7,"title":"我的复习知识大纲","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":390,"comments_nums":10,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-20","id":6,"title":"最简单理解JavaScript的this","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":299,"comments_nums":9,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-20","id":5,"title":"JavaScript复习大纲","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":228,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-18","id":4,"title":"JS数组去重","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":247,"comments_nums":2,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-17","id":3,"title":"理解JavaScript的原型链","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":270,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-17","id":2,"title":"理解JavaScript的原型","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":354,"comments_nums":4,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}}],"meta":{"current_page":1,"per_page":10,"count":11,"total":11,"total_pages":2}}}
    ctx.response.status = 200;
    ctx.body = categoryList;
    }
    articleList(ctx) {
        // 返回结果
     let articleList = {"msg":"success","errorCode":0,"data":{"data":[{"created_at":"2019-08-20","id":12,"title":"DNS预解析","author":"梁凤波","cover":"http://cdn.boblog.com/FvXZiyYKefJ9_HrxbeRiU2jNVJC2","category_id":"5","browse":1237,"comments_nums":35,"category_detail":{"id":5,"name":"Node.js","key":"nodejs","parent_id":0}},{"created_at":"2019-07-09","id":11,"title":"理解JavaScript执行上下文","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":1372,"comments_nums":53,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-27","id":9,"title":"ES6解构-对象解构","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":787,"comments_nums":26,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-26","id":8,"title":"ES6块级作用域-let-const","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":333,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-25","id":7,"title":"我的复习知识大纲","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":390,"comments_nums":10,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-20","id":6,"title":"最简单理解JavaScript的this","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":299,"comments_nums":9,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-20","id":5,"title":"JavaScript复习大纲","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":228,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-18","id":4,"title":"JS数组去重","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":247,"comments_nums":2,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-17","id":3,"title":"理解JavaScript的原型链","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":270,"comments_nums":5,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}},{"created_at":"2019-06-17","id":2,"title":"理解JavaScript的原型","author":"梁凤波","cover":"http://cdn.boblog.com/FmdNNoR1MRtgvmQD1KwaKzbkL_i7","category_id":"3","browse":354,"comments_nums":4,"category_detail":{"id":3,"name":"JavaScript","key":"JavaScript","parent_id":0}}],"meta":{"current_page":1,"per_page":10,"count":11,"total":11,"total_pages":2}}}
    ctx.response.status = 200;
    ctx.body = articleList;
    }
}
module.exports = new CategoryCtl()